title:              Patrick McGuire
email:              pmcguire96@gmail.com
description:        A Blog Made for Patrick
author:             Patrick
baseurl:            ""
url:                "https://pmcguire96.github.io"

# Social Profiles
twitter_username:   mcguire_patrick
github_username:    pmcguire96
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
